name: github pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: finsberg/fenics-extra
    steps:
      - uses: actions/checkout@v4

      - name: Cache
        id: cache-primes
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/instant
            ~/.cache/dijitso
            ~/.cache/pip
            docs/_build/jupyter_execute
          key: cache_v5
          restore-keys: |
            cache_v5

      - name: Upgrade pip
        run: |
          # install pip=>20.1 to use "pip cache dir"
          python3 -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          python3 -m pip install ".[docs]"

      - name: Build docs
        run: |
          make docs

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/_build/html
