name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      run: |
        sudo apt-get install python3-dev python3-pip
        sudo python -m pip install setuptools
    - name: Install FEniCS
      run: |
        sudo apt-get install software-properties-common
        sudo add-apt-repository ppa:fenics-packages/fenics
        sudo apt-get update
        sudo apt-get install --no-install-recommends fenics
    - name: Install dependencies
      run: |
        make dev
    - name: Lint with flake8
      run: |
        make lint
    - name: Type checking with mypy
      run: |
        make type
    - name: Test with pytest
      run: |
        make test
