name: CI

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/scientificcomputing/fenics-gmsh:2024-02-19"

    steps:
      - uses: actions/checkout@v4

      - name: Cache
        id: cache-primes
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/instant
            ~/.cache/dijitso
            ~/.cache/pip
          key: cache_v2
          restore-keys: |
            cache_v2

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install -e ".[test,dev]"

      - name: Run flake8
        run: |
          python3 -m flake8 fenics_plotly tests

      - name: Run black
        run: |
          python3 -m black --check fenics_plotly tests

      - name: Run mypy
        run: |
          python3 -m mypy fenics_plotly tests

      - name: Test with pytest
        run: |
          python3 -m pytest
