name: CI

on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    container:
      image: quay.io/fenicsproject/stable:latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache
        id: cache-primes
        uses: actions/cache@v2
        with:
          path: |
            ~/.cache/instant
            ~/.cache/dijitso
            ~/.cache/pip
          key: cache_v1
          restore-keys: |
            cache_v1

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install h5py --no-binary=h5py
          python3 -m pip install -e ".[test,dev]"

      - name: Run flake8
        run: |
          python3 -m flake8 fenics_plotly tests

      - name: Run black
        run: |
          python3 -m black --check fenics_plotly tests

      - name: Run mypy
        run: |
          python3 -m mypy fenics_plotly tests

      - name: Test with pytest
        run: |
          python3 -m pytest
      - name: Coverage report
        uses: codecov/codecov-action@v1
        with:
          fail_ci_if_error: true
          files: ./coverage.xml
